Repository minikopi/sekolah, pull requests merged in 2023-05, with the labels that each got.

#112 Invoice
  app/Http/Controllers/Datatables/InvoiceDatatables.php
  app/Http/Controllers/InvoiceController.php
  app/Http/Controllers/InvoiceDetailController.php
  app/Http/Controllers/PayInvoiceController.php
  app/Http/Controllers/PublishInvoiceController.php
  app/Http/Controllers/TransactionController.php
  app/Http/Requests/InvoiceDetailRequest.php
  app/Http/Requests/InvoiceRequest.php
  app/Http/Requests/PayInvoiceRequest.php
  app/Models/Invoice.php
  app/Models/InvoiceDetail.php
  app/Models/Scopes/InvoiceScope.php
  app/Providers/FortifyServiceProvider.php
  config/app.php
  database/migrations/2023_04_18_094329_rename_table_invoice_details_table.php
  database/migrations/2023_04_18_153044_add_payment_status_to_invoices_table.php
  database/seeders/Permissions/InvoiceDetailSeeder.php
  database/seeders/Permissions/InvoiceSeeder.php
  database/seeders/PermissionsSeeder.php
  lang/en/auth.php
  lang/en/pagination.php
  lang/en/passwords.php
  lang/en/validation.php
  lang/id/auth.php
  lang/id/pagination.php
  lang/id/passwords.php
  lang/id/validation.php
  resources/views/layout/sidebar.blade.php
  resources/views/pages/confirm-password.blade.php
  resources/views/pages/invoices/create.blade.php
  resources/views/pages/invoices/detail/edit.blade.php
  resources/views/pages/invoices/detail/index.blade.php
  resources/views/pages/invoices/edit.blade.php
  resources/views/pages/invoices/index.blade.php
  resources/views/pages/invoices/payment/index.blade.php
  resources/views/pages/transaction/index.blade.php
  routes/datatable.php
  routes/web.php
Labels: enhancement

#116 feat: Tipe pembayaran
  app/Http/Requests/PaymentTypeRequest.php
  app/Models/PaymentType.php
  resources/views/layout/sidebar.blade.php
  resources/views/pages/payment-type/index.blade.php
Labels: enhancement

#114 added report expense
  app/Http/Controllers/Datatables/ExpenseReportDatatables.php
  app/Http/Controllers/ExpenseReportController.php
  resources/views/pages/expense-report/index.blade.php
  resources/views/pages/expense-report/list.blade.php
  routes/datatable.php
  routes/web.php
Labels: enhancement

#119 Invoice Report & things
  app/Exports/InvoiceExport.php
  app/Http/Controllers/Invoice/InvoiceReportController.php
  database/seeders/Permissions/InvoiceSeeder.php
  resources/views/exports/report-invoice-pdf.blade.php
  resources/views/exports/report-invoice.blade.php
  resources/views/layout/sidebar.blade.php
  resources/views/pages/invoices/report/index.blade.php
  resources/views/pages/students/export.blade.php
  routes/web.php
Labels: enhancement

#123 Transaksi increment/decrement Wallet
  app/Actions/Invoice/AddToInvoice.php
  app/Actions/Wallet/WalletTransaction.php
  app/Http/Controllers/Datatables/WalletDatatables.php
  app/Http/Controllers/Invoice/PayInvoiceController.php
  app/Http/Controllers/TransactionController.php
  app/Http/Controllers/WalletController.php
  app/Http/Requests/WalletRequest.php
  app/Models/Wallet.php
  app/Models/WalletLog.php
  resources/views/pages/wallet/create.blade.php
  resources/views/pages/wallet/edit.blade.php
Labels: enhancement

#132 Improvemet Wallet
  app/Http/Controllers/Datatables/WalletDatatables.php
  app/Http/Controllers/Datatables/WalletLogDatatables.php
  app/Http/Controllers/Wallet/TopUpWalletController.php
  app/Http/Controllers/Wallet/WalletController.php
  app/Http/Controllers/Wallet/WalletLogController.php
  app/Http/Requests/WalletTopUpRequest.php
  database/migrations/2023_05_10_112635_add_danabos_column_to_wallets_table.php
  database/seeders/Permissions/WalletSeeder.php
  resources/views/pages/wallet/create.blade.php
  resources/views/pages/wallet/index.blade.php
  resources/views/pages/wallet/logs.blade.php
  resources/views/pages/wallet/topup.blade.php
  routes/datatable.php
  routes/web.php
Labels: enhancement

#133 feat: can edit/remove dana bos flag ❌
  app/Http/Controllers/Wallet/WalletController.php
  resources/views/pages/wallet/edit.blade.php
Labels: enhancement

#134 fix: permission
  app/Http/Controllers/AssignClassroomStudentController.php
  app/Http/Controllers/Datatables/ExpenseDatatables.php
  app/Http/Controllers/Datatables/InvoiceDatatables.php
  app/Http/Controllers/Datatables/PaymentTypeDatatables.php
  app/Http/Controllers/Datatables/StudentDatatables.php
  app/Http/Controllers/Datatables/TuitionDatatables.php
  app/Http/Controllers/Datatables/WalletDatatables.php
  database/seeders/Permissions/ExpenseSeeder.php
  database/seeders/Permissions/InvoiceSeeder.php
  database/seeders/Permissions/TransactionSeeder.php
  database/seeders/Permissions/WalletSeeder.php
  resources/views/components/datatable-action.blade.php
  resources/views/layout/sidebar.blade.php
  resources/views/pages/academy-year/index.blade.php
  resources/views/pages/assign-classroom-student/index.blade.php
  resources/views/pages/classroom/index.blade.php
  resources/views/pages/expense/index.blade.php
  resources/views/pages/grade/index.blade.php
  resources/views/pages/home.blade.php
  resources/views/pages/invoices/index.blade.php
  resources/views/pages/payment-type/index.blade.php
  resources/views/pages/students/index.blade.php
  resources/views/pages/tuition-type/index.blade.php
  resources/views/pages/tuition/index.blade.php
  resources/views/pages/users/index.blade.php
  resources/views/pages/wallet/index.blade.php
Labels: documentation

#138 feat: Ubah informasi sekolah, profil diri, dan password
  app/Http/Controllers/Invoice/InvoiceController.php
  app/Http/Controllers/Profile/EditPasswordController.php
  app/Http/Controllers/Profile/EditProfileController.php
  app/Http/Controllers/School/SchoolProfileController.php
  app/Http/Requests/SchoolProfileRequest.php
  app/Http/Requests/UserPasswordRequest.php
  app/Http/Requests/UserProfileRequest.php
  app/Models/Staff.php
  app/Models/User.php
  database/migrations/2023_05_11_142625_add_biodata_to_staff_table.php
  database/seeders/Permissions/SchoolSeeder.php
  resources/views/layout/sidebar.blade.php
  resources/views/layout/topbar-right.blade.php
  resources/views/pages/school/profile/index.blade.php
  resources/views/pages/users/password.blade.php
  resources/views/pages/users/profile.blade.php
  routes/web.php
Labels: enhancement

#143 feat: Profil, password and its middleware
  app/Http/Controllers/UsersController.php
  database/migrations/2023_05_12_111405_add_withholding_balance_to_wallets_table.php
  database/seeders/Permissions/SchoolSeeder.php
  resources/views/layout/sidebar.blade.php
  resources/views/pages/school/profile/index.blade.php
Labels: enhancement

#158 Bugfixes
  app/Http/Controllers/Datatables/ExpenseApprovalDatatables.php
  app/Http/Controllers/Datatables/InvoiceDatatables.php
  app/Http/Controllers/Datatables/TuitionApprovalDatatables.php
  app/Http/Controllers/ExpenseApprovalController.php
  app/Http/Controllers/ExpenseController.php
  app/Http/Controllers/ExpenseDetailController.php
  app/Http/Controllers/Invoice/VoidInvoiceController.php
  app/Http/Controllers/TuitionApprovalController.php
  app/Http/Requests/ExpenseRequest.php
  app/Observers/ExpenseDetailObserver.php
  app/Providers/EventServiceProvider.php
  database/migrations/2023_04_05_092632_create_expenses_table.php
  resources/views/layout/sidebar.blade.php
  resources/views/notifications/expense-approval.blade.php
  resources/views/pages/expense-approval/detail.blade.php
  resources/views/pages/expense/detail/create.blade.php
  resources/views/pages/invoices/index.blade.php
  resources/views/pages/tuition-approval/detail.blade.php
  resources/views/pages/tuition-approval/index.blade.php
Labels: bug, enhancement

#165 fix: display/hide staff photo 🔥
  resources/views/pages/staff/edit.blade.php
Labels: bug

#167 WIP: Testing
  app/Http/Controllers/Invoice/PayInvoiceController.php
  app/Http/Controllers/Invoice/PublishInvoiceController.php
  composer.json
  composer.lock
  database/factories/InvoiceDetailFactory.php
  database/factories/InvoiceFactory.php
  database/factories/WalletFactory.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/seeders/Permissions/InvoiceDetailSeeder.php
  database/seeders/Permissions/InvoiceSeeder.php
  database/seeders/PermissionsSeeder.php
  tests/Datasets/School.php
  tests/Feature/AcademyYearsTest.php
  tests/Feature/Console/Commands/PublishTuitionTest.php
  tests/Feature/InvoiceDetailTest.php
  tests/Feature/InvoiceTest.php
  tests/Feature/NotreDameTest.php
  tests/Pest.php
  tests/TestCase.php
Labels: documentation

#191 join migrations 🔥
  database/migrations/2023_03_06_035951_create_tuitions_table.php
  database/migrations/2023_04_05_092632_create_expenses_table.php
  database/migrations/2023_05_17_154918_add_columns_to_expense_table.php
  database/migrations/2023_05_17_154919_add_columns_to_tuition_table.php
Labels: documentation

#194 Fix/test
  database/factories/PaymentTypeFactory.php
  database/factories/WalletFactory.php
  tests/Feature/PaymentTypeTest.php
  tests/Feature/TuitionTypeTest.php
  tests/Pest.php
  tests/TestCase.php
Labels: documentation

#211 Fix invoice
  app/Helper/globals.php
  app/Http/Controllers/Invoice/InvoiceController.php
  app/Http/Controllers/Invoice/InvoiceDetailController.php
  app/Http/Controllers/Invoice/PublishInvoiceController.php
  app/Http/Requests/InvoiceDetailRequest.php
  app/Http/Requests/InvoiceRequest.php
  resources/views/pages/invoices/create.blade.php
  resources/views/pages/invoices/edit.blade.php
  resources/views/pages/invoices/index.blade.php
Labels: bug
