Repository minikopi/sekolah, pull requests merged in 2023-04, with the labels that each got.

#83 Generate tuition
  app/Console/Commands/PublishTuition.php
  app/Jobs/PublishMonthlyTuitions.php
  app/Models/Student.php
  app/Models/StudentTuition.php
  app/Models/TuitionType.php
  app/Notifications/TuitionNotification.php
  database/migrations/2023_04_11_135947_create_job_batches_table.php
  database/migrations/2023_04_12_111519_create_jobs_table.php
  resources/views/notifications/tuition.blade.php
  resources/views/pages/tuition/create.blade.php
  resources/views/pages/tuition/edit.blade.php
  resources/views/pages/tuition/index.blade.php
  tests/Feature/Console/Commands/PublishTuitionTest.php
Labels: enhancement

#85 feat: sidebar for expense 🐒
  resources/views/layout/sidebar.blade.php
Labels: enhancement

#86 feat: transaksi tuition 🔥
  app/Http/Controllers/Datatables/TransactionDatatables.php
  app/Http/Controllers/TransactionController.php
  app/Models/Student.php
  app/Models/StudentTuition.php
  app/Models/StudentTuitionPaymentHistory.php
  app/Notifications/PaidTuitionNotification.php
  app/Notifications/PartialTuitionNotification.php
  database/migrations/2023_04_12_161019_add_payment_type_id_to_student_tuition_payment_histories_table.php
  resources/views/components/datatable-action.blade.php
  resources/views/layout/sidebar.blade.php
  resources/views/notifications/paid-tuition.blade.php
  resources/views/notifications/partial-tuition.blade.php
  resources/views/pages/transaction/index.blade.php
  resources/views/pages/transaction/list.blade.php
  resources/views/pages/transaction/store.blade.php
  routes/datatable.php
Labels: enhancement

#96 fix Bug Transaction #91
  app/Http/Controllers/TransactionController.php
Labels: bug, enhancement

#90 feat: laporan transaksi 🔥
  app/Http/Controllers/Datatables/TransactionReportDatatables.php
  app/Http/Controllers/TransactionReportController.php
  app/Models/StudentTuitionPaymentHistory.php
  database/seeders/Permissions/TransactionReportSeeder.php
  database/seeders/PermissionsSeeder.php
  resources/views/layout/sidebar.blade.php
  resources/views/pages/transaction-report/index.blade.php
  resources/views/pages/transaction-report/list.blade.php
  routes/datatable.php
  routes/web.php
Labels: enhancement

#101 Fix tuition request & only show AY based status years registration, started
  app/Http/Controllers/TuitionController.php
  app/Http/Requests/TuitionRequest.php
Labels: bug

#100 fix: tidak boleh kelebihan bayar ❌
  app/Http/Controllers/TransactionController.php
Labels: bug

#99 Fix things
  .env.example
  app/Http/Controllers/AcademyYearController.php
  app/Http/Controllers/Datatables/AcademyYearDatatables.php
  app/Http/Controllers/SchoolSelectorController.php
  app/Http/Requests/AcademyYearRequest.php
  app/Models/AcademicYear.php
  app/Providers/FortifyServiceProvider.php
  resources/views/layout/footer.blade.php
  resources/views/layout/sidebar.blade.php
  resources/views/layout/topbar-right.blade.php
  resources/views/pages/academy-year/create.blade.php
  resources/views/pages/academy-year/edit.blade.php
Labels: bug, enhancement

#103 chore: fix menu laporan pembayaran sekolah 🔥
  resources/views/layout/sidebar.blade.php
  routes/web.php
Labels: enhancement

#104 fix: session navbar academic year 🔧
  app/Http/Controllers/SchoolSelectorController.php
  app/Providers/FortifyServiceProvider.php
Labels: bug
